### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by eMCeee89**
This pull request is to fix the issue where os.mkdir is unable to recursively create directories.
os.makedirs is working perfectly making this python script more compact

### CODE REVIEW

**Comment by kantuni** [comment]
Thanks for the support 👍 
Can you please provide a screenshot of a bug described?

**Comment by eMCeee89** [comment]
I received os.mkdir() No such file or directory
I can try to reproduce the error if you want today but I think the change done in this pull request is simple and very very easy to understand. Just check what os.makedirs() does, e.g. here:
http://stackoverflow.com/questions/37948294/the-difference-between-os-mkdir-and-os-makedirs

**Comment by kantuni** [comment]
Can you please send the steps to reproduce the problem, and a screenshot with the error?
That would help a lot. 

Thanks

**Comment by kantuni** [comment]
Dear @eMCeee89,

We will merge the pull request as soon as you provide some screenshots of the bug described, and the steps to reproduce it. It is incredibly important for us to see the cause, as we have similar projects in which this problem may occur.

Thank you for your time.

**Pull request merged**
